### ISSUE TITLE
Post method not works for products

### ISSUE THREAD

**Issue by ghost** [goldenplanetdk/api-example#3]
$response = $apiClient->post('products', ['query' => ['product'=>['a','title' => 'AAAAA']]]);

Is it correct way to post product? Please give me a example to post product from the API.

The error is 

Access token: NWExMDUyMmQzODI2ZmRjYmU4ZTM2OGY3NDc2YmQ5NzNjZmIxYjVkNmZmNDI5ZWQ3ZjdjMGJmYzc1MGNlYTdjOQ
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST http://demo24491.gpdemo.com/api/v1/products?product%5B0%5D=a&product%5Btitle%5D=AAAAA` resulted in a `400 Bad Request` response: {"code":400,"message":"Validation Failed","errors":{"children":{"title":{"errors":["This value should not be null."]},"i (truncated...) ' in C:\xampp1\htdocs\api\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:107 Stack trace: #0 C:\xampp1\htdocs\api\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 C:\xampp1\htdocs\api\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp{closure}(Object(GuzzleHttp\Psr7\Response)) #2 C:\xampp1\htdocs\api\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 C:\xampp1\htdocs\api\vendor\guzzlehttp\promises\src\TaskQueue.php(6 in C:\xampp1\htdocs\api\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 107

**Comment by eugenegp** [comment]
@Suwarnakumar see updated example in `example/get_token_guzzle.php`

you should use `form_params` option to send product data

``` php
$productData = [
    'title' => 'Updated Product',
];
$response = $apiClient->post('products', ['form_params' => $productData])
    ->getBody();
```

**Comment by ghost** [comment]
Thank you for your example 
It works perfectly

**Comment by ghost** [comment]
can you give me an example to add image for product post ?
